-- ════════════════════════════════════════════════════════════════════════
-- Ximo — NCAA D1 men's swimming program directory seed.
-- Source: the athletics-site coach/roster links provided. Factual directory
-- data (school name, official site, coaches page). Apply with a UTF-8 paste.
-- ════════════════════════════════════════════════════════════════════════

insert into public.ncaa_programs (slug, name, website, coaches_url) values
  ('texas-am',          'Texas A&M',            'https://12thman.com',            'https://12thman.com/sports/swimdive/coaches'),
  ('arizona',           'Arizona',              'https://arizonawildcats.com',    'https://arizonawildcats.com/sports/mens-swimming-and-diving/coaches'),
  ('bellarmine',        'Bellarmine',           'https://athletics.bellarmine.edu','https://athletics.bellarmine.edu/sports/mens-swimming/coaches'),
  ('auburn',            'Auburn',               'https://auburntigers.com',       'https://auburntigers.com/sports/swimming-diving/roster'),
  ('american',          'American',             'https://aueagles.com',           'https://aueagles.com/sports/swimming-and-diving/roster#sidearm-roster-coaches'),
  ('ball-state',        'Ball State',           'https://ballstatesports.com',    'https://ballstatesports.com/sports/mens-swimming-and-diving/coaches'),
  ('boston-college',    'Boston College',       'https://bceagles.com',           'https://bceagles.com/sports/swimming-and-diving/roster'),
  ('binghamton',        'Binghamton',           'https://binghamtonbearcats.com', 'https://binghamtonbearcats.com/sports/mens-swimming-and-diving/coaches'),
  ('delaware',          'Delaware',             'https://bluehens.com',           'https://bluehens.com/sports/mswim/coaches'),
  ('brown',             'Brown',                'https://brownbears.com',         'https://brownbears.com/sports/mswim/coaches'),
  ('bryant',            'Bryant',               'https://bryantbulldogs.com',     'https://bryantbulldogs.com/sports/mens-swimming-and-diving/coaches'),
  ('bucknell',          'Bucknell',             'https://bucknellbison.com',      'https://bucknellbison.com/sports/mens-swimming-and-diving/coaches'),
  ('byu',               'BYU',                  'https://byucougars.com',         'https://byucougars.com/staff-directory/department/swimming-diving'),
  ('california',        'California',           'https://calbears.com',           'https://calbears.com/sports/mens-swimming-and-diving/coaches'),
  ('california-baptist','California Baptist',   'https://cbulancers.com',         'https://cbulancers.com/sports/mens-swimming-and-diving/coaches'),
  ('colgate',           'Colgate',              'https://colgateathletics.com',   'https://colgateathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('cornell',           'Cornell',              'https://cornellbigred.com',      'https://cornellbigred.com/sports/mens-swimming-and-diving/coaches'),
  ('cleveland-state',   'Cleveland State',      'https://csuvikings.com',         'https://csuvikings.com/sports/mens-swimming-and-diving/coaches'),
  ('dartmouth',         'Dartmouth',            'https://dartmouthsports.com',    'https://dartmouthsports.com/sports/mens-swimming-and-diving/coaches'),
  ('davidson',          'Davidson',             'https://davidsonwildcats.com',   'https://davidsonwildcats.com/sports/mens-swimming-and-diving/coaches'),
  ('denver',            'Denver',               'https://denverpioneers.com',     'https://denverpioneers.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('drexel',            'Drexel',               'https://drexeldragons.com',      'https://drexeldragons.com/sports/mens-swimming-and-diving/coaches'),
  ('eastern-illinois',  'Eastern Illinois',     'https://eiupanthers.com',        'https://eiupanthers.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('fairfield',         'Fairfield',            'https://fairfieldstags.com',     'https://fairfieldstags.com/sports/mens-swimming-and-diving/coaches'),
  ('florida-atlantic',  'Florida Atlantic',     'https://fausports.com',          'https://fausports.com/sports/swimming-and-diving/roster'),
  ('notre-dame',        'Notre Dame',           'https://fightingirish.com',      'https://fightingirish.com/sports/swim/roster'),
  ('florida',           'Florida',              'https://floridagators.com',      'https://floridagators.com/sports/mens-swimming-and-diving/coaches'),
  ('fordham',           'Fordham',              'https://fordhamsports.com',      'https://fordhamsports.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('providence',        'Providence',           'https://friars.com',             'https://friars.com/sports/swimming-and-diving/roster'),
  ('south-carolina',    'South Carolina',       'https://gamecocksonline.com',    'https://gamecocksonline.com/sports/swimming/roster/#coaches'),
  ('grand-canyon',      'Grand Canyon',         'https://gculopes.com',           'https://gculopes.com/sports/mens-swimming-and-diving/roster'),
  ('georgia',           'Georgia',              'https://georgiadogs.com',        'https://georgiadogs.com/sports/msd/coaches'),
  ('army',              'Army',                 'https://goarmywestpoint.com',    'https://goarmywestpoint.com/sports/mens-swimming-and-diving/coaches'),
  ('cincinnati',        'Cincinnati',           'https://gobearcats.com',         'https://gobearcats.com/sports/swimming-and-diving/roster'),
  ('maine',             'Maine',                'https://goblackbears.com',       'https://goblackbears.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('st-bonaventure',    'St. Bonaventure',      'https://gobonnies.com',          'https://gobonnies.com/sports/mens-swimming-and-diving/coaches'),
  ('rider',             'Rider',                'https://gobroncs.com',           'https://gobroncs.com/sports/swimming-and-diving/coaches'),
  ('louisville',        'Louisville',           'https://gocards.com',            'https://gocards.com/sports/swimming-and-diving/roster'),
  ('columbia',          'Columbia',             'https://gocolumbialions.com',    'https://gocolumbialions.com/sports/mens-swimming-and-diving/coaches'),
  ('harvard',           'Harvard',              'https://gocrimson.com',          'https://gocrimson.com/sports/mens-swimming-and-diving/coaches'),
  ('duke',              'Duke',                 'https://goduke.com',             'https://goduke.com/sports/swimming-and-diving/coaches'),
  ('la-salle',          'La Salle',             'https://goexplorers.com',        'https://goexplorers.com/sports/mens-swimming-and-diving/coaches'),
  ('tcu',               'TCU',                  'https://gofrogs.com',            'https://gofrogs.com/sports/swimming-and-diving/coaches'),
  ('canisius',          'Canisius',             'https://gogriffs.com',           'https://gogriffs.com/sports/swimming-and-diving/coaches'),
  ('north-carolina',    'North Carolina',       'https://goheels.com',            'https://goheels.com/sports/swimming-and-diving/coaches'),
  ('holy-cross',        'Holy Cross',           'https://goholycross.com',        'https://goholycross.com/sports/mens-swimming-and-diving/coaches'),
  ('south-dakota-state','South Dakota State',   'https://gojacks.com',            'https://gojacks.com/sports/mswim/coaches'),
  ('manhattan',         'Manhattan',            'https://gojaspers.com',          'https://gojaspers.com/sports/mens-swimming-and-diving/coaches'),
  ('oakland',           'Oakland',              'https://goldengrizzlies.com',    'https://goldengrizzlies.com/sports/swimming-and-diving/coaches'),
  ('lafayette',         'Lafayette',            'https://goleopards.com',         'https://goleopards.com/sports/swimming-and-diving/coaches'),
  ('george-mason',      'George Mason',         'https://gomason.com',            'https://gomason.com/sports/mens-swimming-and-diving/coaches'),
  ('nc-state',          'NC State',             'https://gopack.com',             'https://gopack.com/sports/swimming-and-diving/coaches'),
  ('minnesota',         'Minnesota',            'https://gophersports.com',       'https://gophersports.com/sports/mens-swimming-and-diving/coaches'),
  ('princeton',         'Princeton',            'https://goprincetontigers.com',  'https://goprincetontigers.com/sports/mswim/coaches'),
  ('penn-state',        'Penn State',           'https://gopsusports.com',        'https://gopsusports.com/staff-directory/department/swimming-diving'),
  ('marist',            'Marist',               'https://goredfoxes.com',         'https://goredfoxes.com/sports/mens-swimming-and-diving/coaches'),
  ('csu-bakersfield',   'CSU Bakersfield',      'https://gorunners.com',          'https://gorunners.com/sports/mens-swimming-and-diving/coaches'),
  ('seattle-u',         'Seattle U',            'https://goseattleu.com',         'https://goseattleu.com/sports/mens-swimming/roster'),
  ('stanford',          'Stanford',             'https://gostanford.com',         'https://gostanford.com/staff-directory/department/mens-swimming-diving'),
  ('boston-university', 'Boston University',     'https://goterriers.com',         'https://goterriers.com/sports/mens-swimming-and-diving/coaches'),
  ('wyoming',           'Wyoming',              'https://gowyo.com',              'https://gowyo.com/sports/swimming-and-diving/roster#roster-staff'),
  ('xavier',            'Xavier',               'https://goxavier.com',           'https://goxavier.com/sports/mens-swimming-and-diving/coaches'),
  ('south-dakota',      'South Dakota',         'https://goyotes.com',            'https://goyotes.com/sports/swimming-and-diving/roster#sidearm-roster-coaches'),
  ('green-bay',         'Green Bay',            'https://greenbayphoenix.com',    'https://greenbayphoenix.com/sports/swimming-and-diving/roster#sidearm-roster-coaches'),
  ('georgia-southern',  'Georgia Southern',     'https://gseagles.com',           'https://gseagles.com/sports/swimming-and-diving/coaches'),
  ('georgetown',        'Georgetown',           'https://guhoyas.com',            'https://guhoyas.com/sports/swimming-and-diving/coaches'),
  ('george-washington', 'George Washington',    'https://gwsports.com',           'https://gwsports.com/sports/mens-swimming-and-diving/roster'),
  ('george-washington-2','George Washington (alt)','https://gwusports.com',       'https://gwusports.com/sports/mens-swimming-and-diving/coaches'),
  ('hawaii',            'Hawaii',               'https://hawaiiathletics.com',    'https://hawaiiathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('virginia-tech',     'Virginia Tech',        'https://hokiesports.com',        'https://hokiesports.com/sports/swimming-diving/roster#coaches'),
  ('howard',            'Howard',               'https://hubison.com',            'https://hubison.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('iona',              'Iona',                 'https://ionagaels.com',          'https://ionagaels.com/sports/mens-swimming-and-diving/coaches'),
  ('indiana',           'Indiana',              'https://iuhoosiers.com',         'https://iuhoosiers.com/sports/mens-swimming-and-diving/coaches'),
  ('iu-indianapolis',   'IU Indianapolis',      'https://iuindyjags.com',         'https://iuindyjags.com/sports/mens-swimming-and-diving/coaches'),
  ('lehigh',            'Lehigh',               'https://lehighsports.com',       'https://lehighsports.com/sports/mens-swimming-and-diving/roster'),
  ('le-moyne',          'Le Moyne',             'https://lemoynedolphins.com',    'https://lemoynedolphins.com/sports/mens-swimming-and-diving/coaches'),
  ('lindenwood',        'Lindenwood',           'https://lindenwoodlions.com',    'https://lindenwoodlions.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('loyola-maryland',   'Loyola Maryland',      'https://loyolagreyhounds.com',   'https://loyolagreyhounds.com/sports/swimming-and-diving/coaches'),
  ('lsu',               'LSU',                  'https://lsusports.net',          'https://lsusports.net/sports/sd/roster'),
  ('north-texas',       'North Texas',          'https://meangreensports.com',    'https://meangreensports.com/sports/swimming-and-diving/coaches'),
  ('michigan',          'Michigan',             'https://mgoblue.com',            'https://mgoblue.com/sports/mens-swimming-and-diving/coaches'),
  ('miami-oh',          'Miami (OH)',           'https://miamiredhawks.com',      'https://miamiredhawks.com/sports/swimming-and-diving/coaches'),
  ('missouri-state',    'Missouri State',       'https://missouristatebears.com', 'https://missouristatebears.com/sports/swimming-and-diving/coaches'),
  ('milwaukee',         'Milwaukee',            'https://mkepanthers.com',        'https://mkepanthers.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('monmouth',          'Monmouth',             'https://monmouthhawks.com',      'https://monmouthhawks.com/sports/mens-swimming-and-diving/coaches'),
  ('mount-st-marys',    'Mount St. Mary''s',    'https://mountathletics.com',     'https://mountathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('missouri',          'Missouri',             'https://mutigers.com',           'https://mutigers.com/sports/swimming-and-diving/roster'),
  ('navy',              'Navy',                 'https://navysports.com',         'https://navysports.com/sports/mens-swimming-and-diving/coaches'),
  ('njit',              'NJIT',                 'https://njithighlanders.com',    'https://njithighlanders.com/sports/mens-swimming-and-diving/coaches'),
  ('northern-kentucky', 'Northern Kentucky',    'https://nkunorse.com',           'https://nkunorse.com/sports/mens-swimming/roster#sidearm-roster-coaches'),
  ('northwestern',      'Northwestern',         'https://nusports.com',           'https://nusports.com/sports/mens-swimming-and-diving/coaches'),
  ('old-dominion',      'Old Dominion',         'https://odusports.com',          'https://odusports.com/sports/swimming/roster#coaches'),
  ('ohio-state',        'Ohio State',           'https://ohiostatebuckeyes.com',  'https://ohiostatebuckeyes.com/sports/mens-swim-dive/roster'),
  ('omaha',             'Omaha',                'https://omavs.com',              'https://omavs.com/sports/mens-swimming-diving/roster#sidearm-roster-coaches'),
  ('pacific',           'Pacific',              'https://pacifictigers.com',      'https://pacifictigers.com/sports/mens-swimming-and-diving/coaches'),
  ('penn',              'Penn',                 'https://pennathletics.com',      'https://pennathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('pittsburgh',        'Pittsburgh',           'https://pittsburghpanthers.com', 'https://pittsburghpanthers.com/sports/swimming-and-diving/coaches'),
  ('purdue',            'Purdue',               'https://purduesports.com',       'https://purduesports.com/sports/mens-swimming-diving/roster'),
  ('niagara',           'Niagara',              'https://purpleeagles.com',       'https://purpleeagles.com/sports/mens-swimming-and-diving/coaches'),
  ('queens',            'Queens',               'https://queensathletics.com',    'https://queensathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('georgia-tech',      'Georgia Tech',         'https://ramblinwreck.com',       'https://ramblinwreck.com/sports/c-swim/roster'),
  ('alabama',           'Alabama',              'https://rolltide.com',           'https://rolltide.com/sports/swimming-and-diving/coaches'),
  ('saint-peters',      'Saint Peter''s',       'https://saintpeterspeacocks.com','https://saintpeterspeacocks.com/sports/swimming-and-diving/coaches'),
  ('florida-state',     'Florida State',        'https://seminoles.com',          'https://seminoles.com/sports/mens-swimming-and-diving/roster/?path=mswim'),
  ('seton-hall',        'Seton Hall',           'https://shupirates.com',         'https://shupirates.com/sports/mens-swimming-and-diving/roster'),
  ('southern-illinois', 'Southern Illinois',    'https://siusalukis.com',         'https://siusalukis.com/sports/mens-swimming-and-diving/roster'),
  ('saint-louis',       'Saint Louis',          'https://slubillikens.com',       'https://slubillikens.com/sports/swimming-and-diving/coaches'),
  ('smu',               'SMU',                  'https://smumustangs.com',        'https://smumustangs.com/sports/mens-swimming-and-diving/coaches'),
  ('texas',             'Texas',                'https://texaslonghorns.com',     'https://texaslonghorns.com/sports/mens-swimming-and-diving/coaches'),
  ('arizona-state',     'Arizona State',        'https://thesundevils.com',       'https://thesundevils.com/sports/mens-swimming-diving/roster#coaches'),
  ('st-thomas',         'St. Thomas',           'https://tommiesports.com',       'https://tommiesports.com/sports/mswim/coaches'),
  ('towson',            'Towson',               'https://towsontigers.com',       'https://towsontigers.com/sports/mens-swimming-and-diving/coaches'),
  ('william-mary',      'William & Mary',       'https://tribeathletics.com',     'https://tribeathletics.com/sports/swimming-and-diving/roster#sidearm-roster-coaches'),
  ('uconn',             'UConn',                'https://uconnhuskies.com',       'https://uconnhuskies.com/sports/mswim/coaches'),
  ('uc-santa-barbara',  'UC Santa Barbara',     'https://ucsbgauchos.com',        'https://ucsbgauchos.com/sports/mens-swimming-and-diving/coaches'),
  ('uc-san-diego',      'UC San Diego',         'https://ucsdtritons.com',        'https://ucsdtritons.com/sports/swimming-and-diving/coaches'),
  ('uic',               'UIC',                  'https://uicflames.com',          'https://uicflames.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('incarnate-word',    'Incarnate Word',       'https://uiwcardinals.com',       'https://uiwcardinals.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('kentucky',          'Kentucky',             'https://ukathletics.com',        'https://ukathletics.com/sports/mswim/roster/#coachesBlock'),
  ('umass',             'UMass',                'https://umassathletics.com',     'https://umassathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('umbc',              'UMBC',                 'https://umbcretrievers.com',     'https://umbcretrievers.com/sports/mens-swimming-and-diving/coaches'),
  ('unc-wilmington',    'UNC Wilmington',       'https://uncwsports.com',         'https://uncwsports.com/sports/swimming-diving/roster#sidearm-roster-coaches'),
  ('unlv',              'UNLV',                 'https://unlvrebels.com',         'https://unlvrebels.com/sports/swimming-and-diving/roster#sidearm-roster-coaches'),
  ('usc',               'USC',                  'https://usctrojans.com',         'https://usctrojans.com/sports/mens-swimming-and-diving/coaches'),
  ('southern-indiana',  'Southern Indiana',     'https://usiscreamingeagles.com', 'https://usiscreamingeagles.com/sports/mens-swimming-diving/roster/#sidearm-roster-coaches'),
  ('utah',              'Utah',                 'https://utahutes.com',           'https://utahutes.com/sports/mens-swimming-and-diving/roster'),
  ('tennessee',         'Tennessee',            'https://utsports.com',           'https://utsports.com/sports/mens-swimming-and-diving/coaches/2025-26'),
  ('wisconsin',         'Wisconsin',            'https://uwbadgers.com',          'https://uwbadgers.com/sports/mens-swimming-and-diving/coaches'),
  ('valparaiso',        'Valparaiso',           'https://valpoathletics.com',     'https://valpoathletics.com/sports/mens-swimming-and-diving/coaches'),
  ('villanova',         'Villanova',            'https://villanova.com',          'https://villanova.com/sports/swimming-and-diving/roster#sidearm-roster-coaches'),
  ('virginia',          'Virginia',             'https://virginiasports.com',     'https://virginiasports.com/sports/swimming/roster#coaches'),
  ('vmi',               'VMI',                  'https://vmikeydets.com',         'https://vmikeydets.com/sports/mens-swimming-and-diving/roster#sidearm-roster-coaches'),
  ('wagner',            'Wagner',               'https://wagnerathletics.com',    'https://wagnerathletics.com/sports/mswim/coaches'),
  ('west-virginia',     'West Virginia',        'https://wvusports.com',          'https://wvusports.com/sports/mens-swimming-and-diving/coaches'),
  ('liu',               'LIU',                  'https://www.liuathletics.com',   'https://www.liuathletics.com/sports/mens-swimming-diving/coaches'),
  ('yale',              'Yale',                 'https://yalebulldogs.com',       'https://yalebulldogs.com/sports/mens-swimming-and-diving/coaches'),
  ('youngstown-state',  'Youngstown State',     'https://ysusports.com',          'https://ysusports.com/sports/swim/coaches'),
  ('cal-poly-slo',      'Cal Poly',             'https://gopoly.com',             'https://gopoly.com/sports/mens-swimming-and-diving/coaches'),
  ('gardner-webb',      'Gardner-Webb',         'https://gwbulldogs.com',         'https://gwbulldogs.com/sports/mens-swimming-and-diving/coaches'),
  ('air-force',         'Air Force',            'https://goairforcefalcons.com',  'https://goairforcefalcons.com/sports/mens-swimming-and-diving/coaches'),
  ('evansville',        'Evansville',           'https://gopurpleaces.com',       'https://gopurpleaces.com/sports/swimming-and-diving/coaches')
on conflict (slug) do nothing;
